name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Build
      run: |
        npm ci
        npm run build
    
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        build_dir: build
        keep_history: true
        allow_empty_commit: false
      if: success()
